---
# Delete a CloudFormation stack for the given wrapper service
## Delete CloudFormation stack
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    region: us-east-2

  vars_files:
    - "group_vars/{{region}}.yml"
    - "group_vars/service/{{wrapper_service}}.yml"

  roles:
    - { role: "{{wrapper_service}}", stack_action: delete_stack }
