---
# Query EC2 instances
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    region: us-east-2

  vars_files:
    - roles/ec2_launcher/defaults/main.yml
    - "group_vars/{{region}}.yml"
    - "group_vars/service/{{wrapper_service}}.yml"

  tasks:
    - include: roles/ec2_launcher/tasks/query.yml
