---
# Provision an EC2 instance and configure the given wrapper service
## Create EC2 instances
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    region: us-east-2
    service_tag: "{{wrapper_service}}"
    env_tag: test

  vars_files:
    - "vars/{{region}}.yml"
    - vars/extra_sg_rules.yml
    - "vars/service/{{wrapper_service}}.yml"

  roles:
    - ec2_launcher

## Config EC2 instances
- hosts: ec2hosts
  gather_facts: true
  become: true
  vars:
    ansible_ssh_private_key_file: "{{pem_file}}"
    allowed_hosts: "{{groups['ec2hosts']}}"
    ec2_private_ips: []
    ec2_sg_info: "{{hostvars['localhost'].ec2_sg_info}}"
    ec2_sg_rules: "{{hostvars['localhost'].ec2_sg_rules}}"
    ec2_subnet_info: "{{hostvars['localhost'].ec2_subnet_info}}"
    profile: "{{hostvars['localhost'].ec2_profile}}"
    extra_role: dummy
    region: us-east-2
    web_frontend: apache
    wrapper_service: idservice

  vars_files:
    - "vars/{{region}}.yml"
    - vars/extra_sg_rules.yml
    - vars/monit.yml
    - "vars/service/{{wrapper_service}}.yml"

  pre_tasks:
    - name: Set ec2_private_ips
      set_fact:
        ec2_private_ips: "{{ec2_private_ips}} + ['{{hostvars[item].private_ip}}']"
      with_items: "{{allowed_hosts}}"

  roles:
    - common
    - "{{wrapper_service}}"
    - {role: "{{extra_role}}", when: extra_role != 'dummy'}
